### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

### ISSUE THREAD

**Issue by valix** [fundon/atom-minimap#173]
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

**Atom Version**: 0.155.0
**System**: linux 3.13.0-40-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.7

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:198

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:198:87)
  at MinimapView.module.exports.MinimapView.computeScale (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:192:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at MinimapView.module.exports.MinimapView.onActiveItemChanged (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:472:8)
  at /home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:1:1
  at Pane.module.exports.Pane.observeActiveItem (/usr/share/atom/resources/app/src/pane.js:160:7)
  at MinimapView.module.exports.MinimapView.initialize (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:117:22)
  at MinimapView.View (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:178:25)
  at new MinimapView (/home/valix/SSD/atom/packages/minimap/lib/minimap-view.coffee:86:5)
  at Minimap.module.exports.ViewManagement.onEditorAdded (/home/valix/SSD/atom/packages/minimap/lib/mixins/view-management.coffee:105:16)
  at /home/valix/SSD/atom/packages/minimap/lib/mixins/view-management.coffee:85:37

```

/cc @atom/core

**Comment by vraravam** [comment]
How can one enable the "V4 preview" mode? I have downloaded he v3.5.0 of the plugin....

**Comment by abe33** [comment]
In the settings view for the minimap package there's a `V4 Preview` checkbox, or by setting the `v4Preview` field in your `config.cson` file. You'll have to restart Atom for that setting to take effect.

**Comment by valix** [comment]
With v3.5.0 (V4 preview enabled), the error is no longer displayed.
Problem solved.

**Comment by vraravam** [comment]
Same with me - no more errors!

**Comment by abe33** [comment]
Great to hear :), I'll close the issue when v4 will be officially released.

**Comment by gau1991** [comment]
@abe33 ,
I am also not able to produce same error. :+1:

**Comment by tarasis** [comment]
For me the update of 3.5 (without enabling V4 preview) and Atom 1.66 cleared the problem. I've started twice now and not seen the error.

**Comment by Cronax42** [comment]
Same for me, I think this one's squashed.

**Comment by ericrange** [comment]
Worked for me when i updated my packages

**Comment by abe33** [comment]
Seems like there's no need to keep this ticket alive then :).
