### ISSUE TITLE
Can't open quick settings

### ISSUE THREAD

**Issue by GameplayJDK** [fundon/atom-minimap#194]
When I'd like to access the quick settings first the editor freezes (not the window itself) and then I get the following message in the top right corner of the window:
![screenshot_1](https://cloud.githubusercontent.com/assets/4069263/5627337/19fa7432-9597-11e4-9fe1-08c048f5ff6e.png)
Btw, the link which says "Create issue on the minimap package" seems to be broken.
The error seems to be located in `.atom/packages/minimap/lib/main.coffee` in line `127`. The stack trace reads as the following:
```
TypeError: undefined is not a function
  at atom-workspace.subscriptions.add.atom.commands.add.minimap:open-quick-settings (c:\Users\Gameplay\.atom\packages\minimap\lib\main.coffee:120:14)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61
  at CommandPaletteView.module.exports.CommandPaletteView.confirmed (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\node_modules\command-palette\lib\command-palette-view.js:120:32)
  at CommandPaletteView.module.exports.SelectListView.confirmSelection (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\node_modules\autocomplete\node_modules\atom-space-pen-views\lib\select-list-view.js:335:21)
  at space-pen-div.atom.commands.add.core:confirm (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\node_modules\autocomplete\node_modules\atom-space-pen-views\lib\select-list-view.js:109:19)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:243:29)
  at c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\src\command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:549:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\node_modules\atom-keymap\lib\keymap-manager.js:391:22)
  at HTMLDocument.module.exports.WindowEventHandler.onKeydown (c:\Users\Gameplay\AppData\Local\atom\app-0.165.0\resources\app\src\window-event-handler.js:167:20)
```
There seems to be function called, which isn't defined (at that point in time).

*(Atom v0.165.0; Minimap 3.5.0, v4 Preview deactivated; Windows 8.1)*

**Comment by abe33** [comment]
Thanks for the report, I'll take a look at that.
