### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

### ISSUE THREAD

**Issue by istvankrucsanyica** [fundon/atom-minimap#199]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getPropertyValue' of null

```
At /Users/User/.atom/packages/minimap/lib/minimap-view.coffee:198

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:198:87)
  at MinimapView.module.exports.MinimapView.computeScale (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:192:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at MinimapView.module.exports.MinimapView.onActiveItemChanged (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:472:8)
  at /Users/User/.atom/packages/minimap/lib/minimap-view.coffee:1:1
  at Pane.module.exports.Pane.observeActiveItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:160:7)
  at MinimapView.module.exports.MinimapView.initialize (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:117:22)
  at MinimapView.View (/Applications/Atom.app/Contents/Resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:178:25)
  at new MinimapView (/Users/User/.atom/packages/minimap/lib/minimap-view.coffee:86:5)
  at Minimap.module.exports.ViewManagement.onEditorAdded (/Users/User/.atom/packages/minimap/lib/mixins/view-management.coffee:105:16)
  at /Users/User/.atom/packages/minimap/lib/mixins/view-management.coffee:85:37

```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "trendy-light-ui",
      "flatui"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Remote-FTP, v0.3.0
ascii-codes, v0.3.3
assign-align, v0.1.0
autocomplete-plus, v1.1.0
autocomplete-snippets, v0.3.2
build, v0.22.0
color-picker, v1.2.6
css-snippets, v0.4.0
flatui, v0.4.0
go-plus, v3.0.11
html-id-class-snippets, v1.4.1
http-status-codes, v1.0.2
jsformat, v0.7.18
jslint, v0.10.2
linter-jsonlint, v0.1.2
minimap, v3.4.9
open-last-project, v0.1.1
package-manager-commands, v1.1.0
pretty-json, v0.3.1
project-colorize, v0.1.0
project-manager, v1.14.1
remote-sync, v2.3.1
sassbeautify, v0.2.0
trendy-light-ui, v0.28.1
wakatime, v2.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please see #189, version 3.5.x fix that.

**Comment by istvankrucsanyica** [comment]
Thanks
