### ISSUE TITLE
Uncaught TypeError: Cannot read property '__super__' of undefined

### ISSUE THREAD

**Issue by noseglid** [fundon/atom-minimap#201]
[Enter steps to reproduce below:]

Using V4 preview

1. Click the cogwheel on minimap

**Atom Version**: 0.165.0
**System**: linux 3.13.0-39-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.5.3

### Stack Trace

Uncaught TypeError: Cannot read property '__super__' of undefined

```
At /home/alexo/.atom/packages/minimap/lib/minimap-quick-settings-view.coffee:3

TypeError: Cannot read property '__super__' of undefined
  at Object.<anonymous> (/home/alexo/.atom/packages/minimap/lib/minimap-quick-settings-view.coffee:3:9)
  at Object.<anonymous> (/home/alexo/.atom/packages/minimap/lib/minimap-quick-settings-view.coffee:1:1)
  at Module._compile (module.js:468:26)
  at Object.requireCoffeeScript [as .coffee] (/opt/atom/resources/app/src/coffee-cache.js:61:19)
  at Module.load (/opt/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at HTMLDivElement.<anonymous> (/home/alexo/.atom/packages/minimap/lib/minimap-element.coffee:169:37)

```

### Commands

```
     -0:00.0 settings-view:open (atom-text-editor.editor)
```

### Config

```
{
  "core": {
    "useReactEditor": true,
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "tabs",
      "tree-view",
      "symbols-view",
      "minimap-find-and-replace"
    ]
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true,
      "find-and-replace": true,
      "git-diff": true
    },
    "v4Preview": true
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.5
autocomplete-plus, v1.1.0
blackspace, v1.0.0
build, v0.22.1
editor-stats, v0.16.0
git-log, v0.2.0
highlight-selected, v0.7.0
language-actionscript, v0.1.0
language-ini, v1.3.0
linter, v0.9.1
linter-jscs, v1.4.9
linter-jshint, v0.1.0
linter-php, v0.0.11
minimap, v3.5.3
minimap-git-diff, v3.1.0
minimap-highlight-selected, v3.1.0
seti-syntax, v0.2.1
seti-ui, v0.5.1
sublime-tabs, v0.4.8
symbols-tree-view, v0.3.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Looks like there's a trouble with your installation, `atom-space-pen-views` should be installed with the package. Can you confirm the module is properly installed in the `node_modules` directory of the package?

**Comment by noseglid** [comment]
I'm not seeing the issue any more. It is likely it had something to do with https://github.com/atom/atom-space-pen-views/issues/5.

When atom-space-pen-views was fixed, the issue disappeared for me. I'm closing this for now.
