### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

### ISSUE THREAD

**Issue by bogdanrutylo** [fundon/atom-minimap#207]
[Enter steps to reproduce below:]

1. I just installed atom-minimap on a clear atom installation
2. When I am starting atom appears this error

**Atom Version**: 0.165.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getPropertyValue' of null

```
At /home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:198

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:198:87)
  at MinimapView.module.exports.MinimapView.computeScale (/home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:192:27)
  at /home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:170:8
  at Config.module.exports.Config.observeKeyPath (/usr/share/atom/resources/app/src/config.js:568:7)
  at Config.module.exports.Config.observe (/usr/share/atom/resources/app/src/config.js:134:21)
  at MinimapView.module.exports.MinimapView.initialize (/home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:169:36)
  at MinimapView.View (/home/bogdan/.atom/packages/linter/node_modules/space-pen/lib/space-pen.js:184:25)
  at new MinimapView (/home/bogdan/.atom/packages/minimap/lib/minimap-view.coffee:86:5)
  at Minimap.module.exports.ViewManagement.onEditorAdded (/home/bogdan/.atom/packages/minimap/lib/mixins/view-management.coffee:105:16)
  at /home/bogdan/.atom/packages/minimap/lib/mixins/view-management.coffee:85:37

```

### Commands

```
```

### Config

```
{
  "core": {
    "autoHideMenuBar": true,
    "themes": [
      "flat-simple-dark-ui",
      "monokai"
    ]
  }
}
```

### Installed Packages

```coffee
# User
color-picker, v1.2.6
flat-simple-dark-ui, v0.1.1
font-awesome-snippetset, v0.0.6
git-log, v0.2.0
javascript-snippets, v1.0.0
linter, v0.9.1
markdown-format, v2.5.0
minimap, v3.4.9
monokai, v0.9.0
open-last-project, v0.1.1
project-manager, v1.14.1

# Dev
No dev packages
```

/cc @atom/core

**Comment by bogdanrutylo** [comment]
After updating to version 3.5.4 problem was gone. :)
just close it
