### ISSUE TITLE
crashes when buffer moves to another pane

### ISSUE THREAD

**Issue by despairblue** [fundon/atom-minimap#208]
## Repro Steps

1. open two panes
2. open a buffer in pane one with minimap enabled (it does not have to be shown in fact)
3. move the buffer to pane two by whatever means (drag'n drop, move panes package)

**Expected:** move the buffer
**Actual:** buffer crashes after about 5 seconds of doing nothing

Disabling minimap fixes this.

## Stack Trace
```
TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/home/despairblue/.atom/packages/minimap/lib/minimap-view.coffee:196:87)
  at MinimapView.module.exports.MinimapView.computeScale (/home/despairblue/.atom/packages/minimap/lib/minimap-view.coffee:190:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/home/despairblue/.atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at Main.module.exports.ViewManagement.onEditorAdded (/home/despairblue/.atom/packages/minimap/lib/mixins/view-management.coffee:113:12)
  at /home/despairblue/.atom/packages/minimap/lib/mixins/view-management.coffee:93:12
  at /usr/share/atom/resources/app/src/pane.js:151:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.addItem (/home/despairblue/.atom/packages/tab-smart-sort/lib/tab-smart-sort.coffee:60:19)
  at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app/src/pane.js:418:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:555:18)
  at TabBarView.module.exports.TabBarView.onDrop (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:478:23)
  at space-pen-ul.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
```

## Command History

```
     -2:06.3 uri-opened (atom-workspace.workspace.scrollbars-visible-always.theme-ninja-syntax.theme-fantasy-ui)
     -2:01.7 pane-container:active-pane-item-changed (atom-pane-container.panes)
     -2:01.7 editor:detached (atom-text-editor.editor)
     -2:01.7 editor:will-be-removed (atom-text-editor.editor)
     -2:01.7 pane:item-removed (atom-pane.pane.active.with-minimap)
     -2:01.6 pane:item-added (atom-pane.pane)
     -0:07.0 command-palette:toggle (a.btn.btn-error)
     -0:04.7 editor:delete-to-beginning-of-word (atom-text-editor.editor.mini)
  3x -0:03.6 core:backspace (atom-text-editor.editor.mini)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
     -0:00.0 bug-report:open (a.btn.btn-error)
```

## Versions

* **Atom:**       0.168.0
* **Atom-Shell:** 0.20.4
* **OS:**         linux 3.14.26-1-lts
* **Misc**
    * apm  0.117.0
    * npm  1.4.4
    * node 0.10.33
    * python 3.4.2
    * git 2.2.1

---

<small>This report was created in and posted from the Atom editor using the package `bug-report` v0.5.3.</small>

**Comment by abe33** [comment]
Please make sure you have the latest version (3.5.x), it looks a lot like #173 and I believe it's fixed in 3.5.x.

**Comment by despairblue** [comment]
Version 3.5.4 is installed. Upgraded every package and atom today and restartet atom.

**Comment by abe33** [comment]
Hmm, ok, have you `V4 Preview` setting enabled in the minimap

**Comment by despairblue** [comment]
Nope, but enabling it fixes the problem.

**Comment by abe33** [comment]
Ok, so it's a v3 problem only, I'm not sure it worth the fix as it'll be removed soon but if I can find an easy fix I'll publish it.

**Comment by despairblue** [comment]
OK :+1:

**Comment by fundon** [comment]
@despairblue Is it still same issue in latest version(v4.1.4).

**Comment by despairblue** [comment]
@fundon seems to be fixed.
