### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPropertyValue' of null

### ISSUE THREAD

**Issue by purencool** [fundon/atom-minimap#211]
Right mouse click and then tried to copy hi-lighted php code 
.

**Atom Version**: 0.168.0
**System**: linux 3.13.0-43-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.9

### Stack Trace

Uncaught TypeError: Cannot read property 'getPropertyValue' of null

```
At /home/work/.atom/packages/minimap/lib/minimap-view.coffee:198

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:198:87)
  at MinimapView.module.exports.MinimapView.computeScale (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:192:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at MinimapView.module.exports.MinimapView.onActiveItemChanged (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:472:8)
  at /home/work/.atom/packages/minimap/lib/minimap-view.coffee:1:1
  at Pane.module.exports.Pane.observeActiveItem (/opt/atom/resources/app/src/pane.js:160:7)
  at MinimapView.module.exports.MinimapView.initialize (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:117:22)
  at MinimapView.View (/opt/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/lib/space-pen.js:184:25)
  at new MinimapView (/home/work/.atom/packages/minimap/lib/minimap-view.coffee:86:5)
  at Minimap.module.exports.ViewManagement.onEditorAdded (/home/work/.atom/packages/minimap/lib/mixins/view-management.coffee:105:16)
  at /home/work/.atom/packages/minimap/lib/mixins/view-management.coffee:85:37

```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "symbols-view",
      "language-coffee-script"
    ]
  },
  "minimap": {
    "plugins": {
      "selection": true,
      "git-diff": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-ctags, v2.5.5
autoclose-html, v0.13.0
autocomplete-paths, v0.9.1
autocomplete-plus, v1.1.0
color-picker, v1.2.6
docblockr, v0.5.8
drupal, v1.6.0
inline-autocomplete, v0.3.3
linter-php, v0.0.11
minimap, v3.4.9
minimap-color-highlight, v3.0.3
minimap-find-and-replace, v3.0.4
minimap-git-diff, v3.0.11
minimap-highlight-selected, v3.0.0
minimap-selection, v3.0.1
open-last-project, v0.1.1
phpunit-snippets, v0.1.0
project-manager, v1.14.1
symfony-snippets, v0.3.0
vim-mode, v0.22.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Please update to latest version (3.5.4).

**Comment by k4nar** [comment]
I just got the same error when moving a tab to another panel with the version `3.5.4`.

**Comment by Erid** [comment]
Same as @k4nar, it happened to me while moving a file from one pane to another, also the mini map didn't seem to work properly on the right panel (I did View > Panes > Split Left to have my panes split).

**Comment by TheSeamau5** [comment]
Same here. Whenever I try moving panes around I get this issue regardless of how I split the panes.

**Comment by curtiszimmerman** [comment]
I am using minimap version 3.5.4 in atom version 0.169.0 on Linux Mint 17, and just got this error when moving a file to another pane. My stack trace is (obviously) a little different:

```
Uncaught TypeError: Cannot read property 'getPropertyValue' of null
/home/curtisz/.atom/packages/minimap/lib/minimap-view.coffee:196
Hide Stack TraceShow Stack Trace
TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/home/curtisz/.atom/packages/minimap/lib/minimap-view.coffee:196:87)
  at MinimapView.module.exports.MinimapView.computeScale (/home/curtisz/.atom/packages/minimap/lib/minimap-view.coffee:190:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/home/curtisz/.atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at Main.module.exports.ViewManagement.onEditorAdded (/home/curtisz/.atom/packages/minimap/lib/mixins/view-management.coffee:113:12)
  at /home/curtisz/.atom/packages/minimap/lib/mixins/view-management.coffee:93:12
  at /usr/share/atom/resources/app/src/pane.js:151:16
  at Emitter.module.exports.Emitter.emit (/usr/share/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/usr/share/atom/resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.moveItemToPane (/usr/share/atom/resources/app/src/pane.js:418:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:555:18)
  at TabBarView.module.exports.TabBarView.onDrop (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:478:23)
  at space-pen-ul.<anonymous> (/usr/share/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at space-pen-ul.elemData.handle (/usr/share/atom/resources/app/node_modules/archive-view/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)
The error was thrown from the minimap package This issue has already been reported.
```

**Comment by abe33** [comment]
Can you try enabling the v4 preview in the settings to see if it works better or not?

**Comment by Erid** [comment]
That did the trick for me, there are no crashes when moving files between panes and it also fixes the mini-map on the other panes.

Maybe it should be enabled by default and what does v4 preview means?. Thanks for the help :)

**Comment by abe33** [comment]
> Maybe it should be enabled by default and what does v4 preview means?. Thanks for the help :) 

It'll be, when v4 will be release. About its meaning, it's as it says, it enables a preview of the minimap code for version 4. Version 3 and priors were using `space-pen` for the view and was full of various little bug due to the approach choosed at first (no DOM polling, no real model, etc.). Version 4 fixes these things by having a real model, and a custom element view registered with a provider using the new atom mechanism. This bug is a good example of bugs that was immediately fixed just by changing the approach.

**Comment by curtiszimmerman** [comment]
Works for me, too! Thanks for the quick follow-up.

**Comment by purencool** [comment]
As soon as the deb repo updated atom to 1.69.0 the issue went away for me

**Comment by okoriko** [comment]
V4 preview also fixed my problem. Thanks @abe33

**Comment by karai17** [comment]
I tried swapping markdown preview and markdown edit to opposing sides and this error popped up.

**Comment by GabLeRoux** [comment]
Same error thrown while moving a file to the right pane. I had same file opened on left and right pane at first and the scroll preview wasn't showing on right pane. Does the same from left to right. This looks more like what @curtiszimmerman had (https://github.com/fundon/atom-minimap/issues/211#issuecomment-69830920).

### Steps to reproduce

1. Right click beside tab, click `Split Right`
2. Drag left tab to right tab
3. Cry

**Atom Version**: 0.176.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.5.6

### Stack Trace

Uncaught TypeError: Cannot read property 'getPropertyValue' of null

```
At /Users/gableroux/.atom/packages/minimap/lib/minimap-view.coffee:196

TypeError: Cannot read property 'getPropertyValue' of null
  at MinimapView.module.exports.MinimapView.getEditorLineHeight (/Users/gableroux/.atom/packages/minimap/lib/minimap-view.coffee:196:87)
  at MinimapView.module.exports.MinimapView.computeScale (/Users/gableroux/.atom/packages/minimap/lib/minimap-view.coffee:190:27)
  at MinimapView.module.exports.MinimapView.attachToPaneView (/Users/gableroux/.atom/packages/minimap/lib/minimap-view.coffee:250:6)
  at Main.module.exports.ViewManagement.onEditorAdded (/Users/gableroux/.atom/packages/minimap/lib/mixins/view-management.coffee:113:12)
  at /Users/gableroux/.atom/packages/minimap/lib/mixins/view-management.coffee:93:12
  at /opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:165:16
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:348:20)
  at Pane.module.exports.Pane.moveItemToPane (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:432:19)
  at TabBarView.module.exports.TabBarView.moveItemBetweenPanes (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:561:18)
  at TabBarView.module.exports.TabBarView.onDrop (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:484:23)
  at space-pen-ul.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/tabs/lib/tab-bar-view.js:3:61)
  at space-pen-ul.jQuery.event.dispatch (/Users/gableroux/.atom/packages/build/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4430:9)
  at space-pen-ul.elemData.handle (/Users/gableroux/.atom/packages/build/node_modules/atom-space-pen-views/node_modules/space-pen/node_modules/jquery/dist/jquery.js:4116:28)

```

### Commands

```
     -3:03.2 editor:move-to-first-character-of-line (atom-text-editor.editor)
     -3:02.6 core:select-all (atom-text-editor.editor)
     -3:02.0 snippets:next-tab-stop (atom-text-editor.editor)
     -3:02.0 snippets:expand (atom-text-editor.editor)
     -3:02.0 editor:indent (atom-text-editor.editor)
     -3:01.7 core:select-all (atom-text-editor.editor)
     -3:01.5 core:copy (atom-text-editor.editor)
     -2:58.1 snippets:next-tab-stop (atom-text-editor.editor)
     -2:58.1 snippets:expand (atom-text-editor.editor)
     -2:58.1 editor:indent (atom-text-editor.editor)
     -2:57.6 core:select-all (atom-text-editor.editor)
     -2:56.6 core:copy (atom-text-editor.editor)
     -2:03.0 core:close (atom-text-editor.editor)
     -2:00.1 core:select-all (atom-text-editor.editor)
     -1:59.9 core:copy (atom-text-editor.editor)
  2x -1:59.4 core:close (atom-text-editor.editor)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "timecop",
      "vim-mode",
      "symfony-snippets"
    ]
  },
  "minimap": {
    "plugins": {
      "git-diff": true
    }
  }
}
```

### Installed Packages

```coffee
# User
ScssBundle, v0.4.0
angularjs, v0.1.0
ascii-codes, v0.3.3
atom-compile-coffee, v1.3.0
atom-django, v0.2.0
build, v0.23.3
coffee-lint, v0.7.3
coffee-refactor, v0.6.2
color-picker, v1.4.4
css-snippets, v0.5.0
editorconfig, v0.3.0
gist-it, v0.6.4
grunt-runner, v0.6.0
js-refactor, v0.3.0
language-blade, v0.7.0
language-erlang, v2.0.0
language-gitignore, v0.1.1
language-ini, v1.3.0
language-python-django-templates, v0.1.0
laravel, v0.4.2
laravel-facades, v1.0.0
linter, v0.10.1
linter-pylint, v0.2.0
linter-scss-lint, v0.0.11
linter-xmllint, v0.0.5
minimap, v3.5.6
minimap-git-diff, v3.1.1
refactor, v0.4.1
scope-inspector, v0.2.1
travis-ci-status, v0.11.2

# Dev
No dev packages
```

/cc @atom/core

**Comment by vicksonzero** [comment]
same bug as @GabLeRoux

**Comment by bradleyflood** [comment]
Error when splitting 'down' with duplicate tabs

**Comment by fundon** [comment]
Please update to latest version(4.x) and try again.

**Comment by fundon** [comment]
@purencool  @vicksonzero  @bradleyflood  Is it still same issue in the latest version(v4.1.4)?

**Comment by GabLeRoux** [comment]
Updated to `4.1.0` and worked fine, now using `4.1.4` and it seems right, at least, doing the exact steps I described previously, it doesn't break anymore :)

**Comment by fundon** [comment]
Thank you for report. :)
