### ISSUE TITLE
Uncaught TypeError: Cannot read property 'style' of null

### ISSUE THREAD

**Issue by endorama** [fundon/atom-minimap#225]
Steps to reproduce:

1. Open a file ( doesn't matter the type )
2. Close it

**Atom Version**: 0.172.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.4.4

### Stack Trace

Uncaught TypeError: Cannot read property 'style' of null

```
At /.../.atom/packages/minimap/lib/minimap-view.coffee:368

TypeError: Cannot read property 'style' of null
  at MinimapView.module.exports.MinimapView.resetMinimapWidthWithWrap (/.../.atom/packages/minimap/lib/minimap-view.coffee:368:62)
  at MinimapView.module.exports.MinimapView.destroy (/.../.atom/packages/minimap/lib/minimap-view.coffee:203:6)
  at /.../.atom/packages/minimap/lib/mixins/view-management.coffee:122:14
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at TextEditor.module.exports.TextEditor.destroyed (/opt/atom/resources/app/src/text-editor.js:267:27)
  at TextEditor.module.exports.Model.destroy (/opt/atom/resources/app/node_modules/theorist/lib/model.js:218:14)
  at Pane.module.exports.Pane.destroyItem (/opt/atom/resources/app/src/pane.js:449:18)
  at HTMLDivElement.<anonymous> (/opt/atom/resources/app/node_modules/tabs/lib/tab-bar-view.js:172:22)
  at HTMLElement.jQuery.event.dispatch (/opt/atom/resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4676:9)
  at HTMLElement.elemData.handle (/opt/atom/resources/app/node_modules/autocomplete/node_modules/atom-space-pen-views/node_modules/space-pen/vendor/jquery.js:4360:46)

```

### Commands

```
     -0:29.9 window:run-package-specs (tabs-bar.list-inline.tab-bar.inset-panel)
     -0:29.9 command-palette:toggle (tabs-bar.list-inline.tab-bar.inset-panel)
     -0:01.1 project-manager:toggle (atom-pane.pane.active.with-minimap)
     -0:00.0 core:confirm (atom-text-editor.editor.mini)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "open-on-github",
      "archive-view",
      "vim-mode",
      "valign",
      "pomodoro",
      "language-arduino"
    ],
    "themes": [
      "seti-ui",
      "tomorrow-night-eighties-syntax"
    ],
    "projectHome": "/.../code",
    "audioBeep": false
  },
  "minimap": {
    "displayPluginsControls": false
  }
}
```

### Installed Packages

```coffee
# User
Sublime-Style-Column-Selection, v1.1.3
language-todotxt, v0.6.1
minimap, v3.4.4
project-manager, v1.14.0
seti-ui, v0.3.6
tomorrow-night-eighties-syntax, v0.3.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by abe33** [comment]
Your minimap version is quite behind, please update to the latest version (3.5.6).
