### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by yoshuawuyts** [fundon/atom-minimap#230]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.1
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v3.5.6

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/yoshuawuyts/src/yw/dotfiles/.atom/packages/minimap/lib/mixins/view-management.coffee:85

TypeError: undefined is not a function
  at /Users/yoshuawuyts/src/yw/dotfiles/.atom/packages/minimap/lib/mixins/view-management.coffee:85:7
  at atom-workspace.attachedCallback (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/workspace-view.js:94:18)
  at atom-workspace.handler (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:110:34)
  at atom-workspace.jQuery.event.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at atom-workspace.elemData.handle (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at TextEditorView.jQuery.fn.trigger (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/space-pen-extensions.js:64:23)
  at TextEditorView.module.exports.TextEditorView.afterAttach (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/text-editor-view.js:180:19)
  at callAttachHooks (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/space-pen/lib/space-pen.js:342:67)
  at atom-pane-axis.PaneAxisElement.childAdded (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-axis-element.js:54:14)
  at Emitter.module.exports.Emitter.emit (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneAxis.module.exports.PaneAxis.addChild (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-axis.js:124:27)
  at PaneAxis.module.exports.PaneAxis.insertChildAfter (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-axis.js:174:19)
  at Pane.module.exports.Pane.split (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:658:23)
  at Pane.module.exports.Pane.splitRight (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane.js:626:19)
  at atom-pane.atom.commands.add.pane:split-right (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/pane-element.js:226:30)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/command-registry.js:156:19)
  at Ipc.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/app/src/window-event-handler.js:65:30)
  at Ipc.emit (events.js:107:17)
  at process.<anonymous> (/opt/homebrew-cask/Caskroom/atom/latest/Atom.app/Contents/Resources/atom/renderer/api/lib/ipc.js:22:29)
  at process.emit (events.js:110:17)

```

### Commands

```
     -0:40.0 core:backspace (input.hidden-input)
     -0:39.1 core:move-right (input.hidden-input)
  2x -0:38.3 core:backspace (input.hidden-input)
     -0:36.5 docblockr:parse-enter (input.hidden-input)
     -0:36.5 editor:newline (input.hidden-input)
     -0:34.0 core:move-right (input.hidden-input)
     -0:33.1 core:move-left (input.hidden-input)
     -0:28.0 editor:select-to-end-of-line (input.hidden-input)
     -0:22.0 editor:delete-line (input.hidden-input)
     -0:19.1 docblockr:parse-enter (input.hidden-input)
     -0:19.1 editor:newline (input.hidden-input)
  6x -0:18.5 core:move-up (input.hidden-input)
     -0:13.3 editor:delete-line (input.hidden-input)
  3x -0:10.2 core:undo (input.hidden-input)
     -0:06.4 core:save (input.hidden-input)
     -0:00.0 pane:split-right (input.hidden-input)
```

### Config

```
{
  "core": {
    "themes": [
      "spacegray-eighties-ui",
      "tomorrow-night-eighties"
    ],
    "useReactEditor": true,
    "audioBeep": false
  },
  "minimap": {
    "plugins": {
      "highlight-selected": true
    }
  }
}
```

### Installed Packages

```coffee
# User
atom-alignment, v0.9.3
atom-jsfmt, v0.6.0
autoclose-html, v0.13.0
autocomplete-plus, v1.1.0
color-picker, v1.4.0
cucumber, v0.4.1
docblockr, v0.5.8
editorconfig, v0.3.0
highlight-selected, v0.7.0
http-status-codes, v1.0.2
language-docker, v1.1.2
language-glsl, v0.2.2
language-go, v0.21.0
language-ini, v1.3.0
language-jade, v0.3.0
language-restructuredtext, v0.2.0
language-viml, v0.2.0
linter, v0.10.0
minimap, v3.5.6
minimap-color-highlight, v3.1.0
minimap-highlight-selected, v3.1.0
spacegray-eighties-ui, v0.7.0
tomorrow-night-eighties, v0.3.0
travis-ci-status, v0.11.1
vim-mode, v0.29.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by yoshuawuyts** [comment]
duplicate, apologies.
