### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by queenp** [fundon/atom-minimap#248]
[Enter steps to reproduce below:]

1. Installed
2. Got a big red error box

**Atom Version**: 0.165.0
**System**: linux 3.13.0-44-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.0.2

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /home/foibey/.atom/packages/minimap/lib/minimap-element.coffee:32

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/home/foibey/.atom/packages/minimap/lib/minimap-element.coffee:32:36)
  at Object.createView (/home/foibey/.atom/packages/minimap/lib/minimap-element.coffee:442:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/usr/share/atom/resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/usr/share/atom/resources/app/src/view-registry.js:43:21)
  at /home/foibey/.atom/packages/minimap/lib/main.coffee:269:35
  at Workspace.module.exports.Workspace.observeTextEditors (/usr/share/atom/resources/app/src/workspace.js:265:9)
  at Main.initSubscriptions (/home/foibey/.atom/packages/minimap/lib/main.coffee:265:39)
  at Main.toggle (/home/foibey/.atom/packages/minimap/lib/main.coffee:132:8)
  at Main.activate (/home/foibey/.atom/packages/minimap/lib/main.coffee:101:6)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:227:27)
  at /usr/share/atom/resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:410:21)
  at /usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/usr/share/atom/resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/usr/share/atom/resources/app/src/buffered-process.js:63:47)
  at /usr/share/atom/resources/app/src/buffered-process.js:70:18
  at Socket.<anonymous> (/usr/share/atom/resources/app/src/buffered-process.js:150:18)
  at Socket.emit (events.js:129:20)
  at Pipe.close (net.js:461:12)
  at Ipc.sendSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:39:29)
  at Ipc.sendChannelSync (/usr/share/atom/resources/atom/renderer/api/lib/ipc.js:47:28)
  at BrowserWindow.RemoteMemberFunction [as emit] (/usr/share/atom/resources/atom/renderer/api/lib/remote.js:110:29)
  at ContextMenuManager.module.exports.ContextMenuManager.showForEvent (/usr/share/atom/resources/app/src/context-menu-manager.js:169:33)
  at HTMLDocument.<anonymous> (/usr/share/atom/resources/app/src/window-event-handler.js:138:33)
  at HTMLDocument.handler (/usr/share/atom/resources/app/src/space-pen-extensions.js:112:34)
  at HTMLDocument.jQuery.event.dispatch (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4681:9)
  at HTMLDocument.elemData.handle (/usr/share/atom/resources/app/node_modules/space-pen/vendor/jquery.js:4359:46)

```

### Commands

```
     -0:07.0 editor:select-to-first-character-of-line (input.hidden-input)
  2x -0:00.0 core:confirm (input.hidden-input)
```

### Config

```
{
  "core": {
    "autoHideMenuBar": true
  }
}
```

### Installed Packages

```coffee
# User
behat-atom, v0.1.2
cucumber, v0.4.1
docblockr, v0.5.8
language-SCSS, v0.2.0
language-haml, v0.15.0
linter, v0.10.1
markdown-format, v2.5.0
notebook, v0.4.0
project-manager, v1.15.5
timekeeper, v0.4.0
vim-mode, v0.30.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
Thanks for your report. 
Upgrade your Atom, please.

**Comment by queenp** [comment]
Oh, sorry. Thanks,

**Comment by fundon** [comment]
Is it working?

**Comment by abe33** [comment]
I thinks it should be working, the issue was coming from the `atom.themes` event registration method that was introduced recently. 
BTW the engine field of `package.json` is still not used to prevent installation of packages...

**Comment by fundon** [comment]
> BTW the engine field of package.json is still not used to prevent installation of packages...

I think the Atom should remind user after it checked the engine field.

**Comment by fundon** [comment]
If you need, re-open it. Thanks.
