### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by jorgeliecer** [fundon/atom-minimap#252]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.165.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.1.0

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/jorgeosorio/.atom/packages/minimap/lib/minimap-element.coffee:32

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/Users/jorgeosorio/.atom/packages/minimap/lib/minimap-element.coffee:32:36)
  at Object.createView (/Users/jorgeosorio/.atom/packages/minimap/lib/minimap-element.coffee:472:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:43:21)
  at /Users/jorgeosorio/.atom/packages/minimap/lib/main.coffee:273:35
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:270:16
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (/Applications/Atom.app/Contents/Resources/app/src/pane-container.js:379:27)
  at /Applications/Atom.app/Contents/Resources/app/src/pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app/src/pane.js:313:14)
  at /Applications/Atom.app/Contents/Resources/app/src/workspace.js:494:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:787:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:816:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:749:13)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:557:44
  at flush (/Applications/Atom.app/Contents/Resources/app/node_modules/pathwatcher/node_modules/q/q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
     -0:00.0 window:update-available (atom-workspace.workspace.scrollbars-visible-when-scrolling.theme-base16-tomorrow-dark-theme.theme-atom-dark-ui)
```

### Config

```
{
  "core": {
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "themes": [
      "atom-dark-ui",
      "base16-tomorrow-dark-theme"
    ]
  }
}
```

### Installed Packages

```coffee
# User
minimap, v4.1.0

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
Upgrade Atom

**Comment by fundon** [comment]
Thanks for your report.
If there is still same issue in the latest Atom(v0.177). Please re-open it, if you need.
