### ISSUE TITLE
Minimap doesn't start

### ISSUE THREAD

**Issue by ferranmarlet** [fundon/atom-minimap#257]
Hi, I've seen that minimap is not starting at boot as it used to do. I cannot start it later either. Here I copy the error message show in the console, cheers and thank you for your plugin!

Failed to activate package named 'minimap' TypeError: Cannot read property 'addViewProvider' of undefined
  at Function.MinimapElement.registerViewProvider (/home/ferran/.atom/packages/minimap/lib/minimap-element.coffee:471:13)
  at Main.activate (/home/ferran/.atom/packages/minimap/lib/main.coffee:99:20)
  at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app/src/package.js:198:27)
  at /usr/share/atom/resources/app/src/package.js:184:28
  at Package.module.exports.Package.measure (/usr/share/atom/resources/app/src/package.js:130:15)
  at Package.module.exports.Package.activate (/usr/share/atom/resources/app/src/package.js:178:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app/src/package-manager.js:404:21)
  at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app/src/package-manager.js:393:14)
  at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app/src/package-manager.js:379:19)
  at Atom.module.exports.Atom.startEditorWindow (/usr/share/atom/resources/app/src/atom.js:516:21)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:14:8)
  at Object.<anonymous> (/usr/share/atom/resources/app/src/window-bootstrap.js:29:4)
  at Module._compile (module.js:468:26)
  at Object.Module._extensions..js (module.js:486:10)
  at Module.load (/usr/share/atom/resources/app/node_modules/coffee-script/lib/coffee-script/register.js:45:36)
  at Function.Module._load (module.js:318:12)
  at Module.require (module.js:373:17)
  at require (module.js:392:17)
  at window.onload (file:///usr/share/atom/resources/app/static/index.js:20:25)

**Comment by abe33** [comment]
If you doesn't have the `atom.views` object that mean you have a really outdated version of Atom. I try to keep the `engine` version in `package.json` up-to-date, but it seems that apm doesn't use it yet. My advice would be to update Atom to the latest version (0.177.0).

**Comment by ferranmarlet** [comment]
Thank you, you were right, and it worked like a charm.

**Comment by abe33** [comment]
Great, I'll close this issue then.
