### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by akilhoffer** [fundon/atom-minimap#263]
Uncaught TypeError: undefined is not a function

**Atom Version**: 0.162.0
**System**: Mac OS X 10.10.2
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.1.4

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/Anthony/.atom/packages/minimap/lib/minimap-element.coffee:32

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (/Users/Anthony/.atom/packages/minimap/lib/minimap-element.coffee:32:36)
  at Object.createView (/Users/Anthony/.atom/packages/minimap/lib/minimap-element.coffee:473:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (/Applications/Atom.app/Contents/Resources/app/src/view-registry.js:43:21)
  at /Users/Anthony/.atom/packages/minimap/lib/main.coffee:281:35
  at Workspace.module.exports.Workspace.observeTextEditors (/Applications/Atom.app/Contents/Resources/app/src/workspace.js:265:9)
  at Main.initSubscriptions (/Users/Anthony/.atom/packages/minimap/lib/main.coffee:277:39)
  at Main.toggle (/Users/Anthony/.atom/packages/minimap/lib/main.coffee:144:8)
  at Main.activate (/Users/Anthony/.atom/packages/minimap/lib/main.coffee:108:6)
  at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:227:27)
  at /Applications/Atom.app/Contents/Resources/app/src/package.js:213:28
  at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:159:15)
  at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:207:14)
  at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:410:21)
  at /Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:234:29
  at exit (/Applications/Atom.app/Contents/Resources/app/node_modules/settings-view/lib/package-manager.js:37:16)
  at BufferedProcess.triggerExitCallback (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:59:47)
  at ChildProcess.<anonymous> (/Applications/Atom.app/Contents/Resources/app/src/buffered-process.js:81:18)
  at ChildProcess.emit (events.js:110:17)
  at Process.ChildProcess._handle.onexit (child_process.js:1072:12)

```

/cc @atom/core

**Comment by fundon** [comment]
Upgrade the Atom to the latest version v0.177

**Comment by akilhoffer** [comment]
That's it! Thanks for the very fast reply!
