### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by suryapratap** [fundon/atom-minimap#265]
[Enter steps to reproduce below:]

1. Start Atom

**Atom Version**: 0.165.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.1.4

### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /c:/Users/satra/.atom/packages/minimap/lib/minimap-element.coffee:43

TypeError: undefined is not a function
  at atom-text-editor-minimap.MinimapElement.createdCallback (c:\Users\satra\.atom\packages\minimap\lib\minimap-element.coffee:32:36)
  at Object.createView (c:\Users\satra\.atom\packages\minimap\lib\minimap-element.coffee:473:15)
  at ViewRegistry.module.exports.ViewRegistry.createView (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\view-registry.js:61:72)
  at ViewRegistry.module.exports.ViewRegistry.getView (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\view-registry.js:43:21)
  at c:\Users\satra\.atom\packages\minimap\lib\main.coffee:281:35
  at c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:270:16
  at c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:327:18
  at Emitter.module.exports.Emitter.emit (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at PaneContainer.module.exports.PaneContainer.addedPaneItem (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\pane-container.js:379:27)
  at c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\pane-container.js:366:26
  at Emitter.module.exports.Emitter.emit (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\event-kit\lib\emitter.js:82:11)
  at Pane.module.exports.Pane.addItem (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:334:20)
  at Pane.module.exports.Pane.activateItem (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\pane.js:313:14)
  at c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\src\workspace.js:494:16
  at _fulfilled (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:787:54)
  at self.promiseDispatch.done (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:816:30)
  at Promise.promise.promiseDispatch (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:749:13)
  at c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:557:44
  at flush (c:\Users\satra\AppData\Local\atom\app-0.165.0\resources\app\node_modules\q\q.js:108:17)
  at process._tickCallback (node.js:378:11)

```

### Commands

```
```

### Config

```
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "monokai"
    ],
    "followSymlinks": true
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-plus-async, v0.22.0
html-helper, v0.2.3
jsformat, v0.7.18
markdown-format, v2.5.0
minimap, v4.1.4
monokai, v0.12.0
omnisharp-atom, v0.1.6
pretty-json, v0.3.2
refactor, v0.4.1
web-browser, v0.2.3

# Dev
No dev packages
```

/cc @atom/core

**Comment by fundon** [comment]
Upgrade your Atom >= 0.177

**Comment by fundon** [comment]
After upgrading, there is still same issue, re-open it if you need. Thanks.

**Comment by suryapratap** [comment]
Thank you, I have updated Atom to 0.179, now working just fine :+1:
