### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getScrollTop' of null

### ISSUE THREAD

**Issue by bkarr** [fundon/atom-minimap#273]
[Enter steps to reproduce below:]

1. ...Toggled off minimap 
2. ...

**Atom Version**: 0.179.0
**System**: linux 3.13.0-24-generic
**Thrown From**: [minimap](https://github.com/fundon/atom-minimap) package, v4.2.0

### Stack Trace

Uncaught TypeError: Cannot read property 'getScrollTop' of null

```
At /home/bryk/.atom/packages/minimap/lib/minimap.coffee:179

TypeError: Cannot read property 'getScrollTop' of null
  at Minimap.module.exports.Minimap.getTextEditorScrollRatio (/home/bryk/.atom/packages/minimap/lib/minimap.coffee:179:16)
  at Minimap.module.exports.Minimap.getCapedTextEditorScrollRatio (/home/bryk/.atom/packages/minimap/lib/minimap.coffee:186:50)
  at Minimap.module.exports.Minimap.getScrollTop (/home/bryk/.atom/packages/minimap/lib/minimap.coffee:256:15)
  at Minimap.module.exports.Minimap.getLastVisibleScreenRow (/home/bryk/.atom/packages/minimap/lib/minimap.coffee:247:17)
  at Minimap.module.exports.DecorationManagement.emitRangeChanges (/home/bryk/.atom/packages/minimap/lib/mixins/decoration-management.coffee:167:31)
  at Minimap.module.exports.DecorationManagement.emitDecorationChanges (/home/bryk/.atom/packages/minimap/lib/mixins/decoration-management.coffee:159:6)
  at Minimap.module.exports.DecorationManagement.removeDecoration (/home/bryk/.atom/packages/minimap/lib/mixins/decoration-management.coffee:188:6)
  at /home/bryk/.atom/packages/minimap/lib/mixins/decoration-management.coffee:144:8
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Decoration.module.exports.Decoration.destroy (/opt/atom/resources/app/src/decoration.js:59:20)
  at MinimapSelectionView.module.exports.MinimapSelectionView.removeDecorations (/home/bryk/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:34:17)
  at MinimapSelectionView.module.exports.MinimapSelectionView.destroy (/home/bryk/.atom/packages/minimap-selection/lib/minimap-selection-view.coffee:20:6)
  at /home/bryk/.atom/packages/minimap-selection/lib/minimap-selection.coffee:35:23
  at Emitter.module.exports.Emitter.emit (/opt/atom/resources/app/node_modules/event-kit/lib/emitter.js:82:11)
  at Minimap.module.exports.Minimap.destroy (/home/bryk/.atom/packages/minimap/lib/minimap.coffee:74:14)
  at /home/bryk/.atom/packages/minimap/lib/main.coffee:145:15
  at Map.forEach (native)
  at Main.toggle (/home/bryk/.atom/packages/minimap/lib/main.coffee:144:25)
  at atom-workspace.Main.subscriptionsOfCommands.add.atom.commands.add.minimap:toggle (/home/bryk/.atom/packages/minimap/lib/main.coffee:102:29)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:243:29)
  at CommandRegistry.handleCommandEvent (/opt/atom/resources/app/src/command-registry.js:3:61)
  at CommandRegistry.module.exports.CommandRegistry.dispatch (/opt/atom/resources/app/src/command-registry.js:156:19)
  at EventEmitter.<anonymous> (/opt/atom/resources/app/src/window-event-handler.js:65:30)
  at EventEmitter.emit (events.js:116:17)

```

### Commands

```
  3x -0:50.2 core:page-down (atom-text-editor.editor)
 21x -0:27.4 core:move-down (atom-text-editor.editor.is-focused)
 33x -0:25.6 core:move-up (atom-text-editor.editor.is-focused)
     -0:03.2 minimap:toggle (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "destroyEmptyPanes": false
  },
  "minimap": {
    "plugins": {
      "selection": true,
      "git-diff": true,
      "find-and-replace": true
    }
  }
}
```

### Installed Packages

```coffee
# User
autocomplete-clang, v0.6.2
autocomplete-plus, v2.1.6
indent-guide-improved, v1.1.1
linter, v0.11.1
linter-clang, v2.25.1
minimap, v4.2.0
minimap-find-and-replace, v3.1.0
minimap-git-diff, v3.1.1
minimap-selection, v4.0.1

# Dev
No dev packages
```

**Comment by abe33** [comment]
Thanks for the report, the patch is coming.

**Comment by diegognt** [comment]
Happen to me, right now

**Comment by anjerodesu** [comment]
Happened to me today. Very rare moment as this is the first time I encounter such bug. Anyway, what I'm doing is closing tabs, probably fast enough that this error came up.

**Comment by abe33** [comment]
@diegognt & @anjerodesu If you you have the same Atom version as the initial reporter I urge you to update (Atom has moved past the 1.0.0 milestone now so maintaining old pre-1.0 version is a no go).

If not, can you open a new issue with some details about the context? (the stack of the initial report is irrelevant then).

**Comment by anjerodesu** [comment]
@abe33 yep, sorry about that. Kinda busy earlier that I forgot to check whether the issue is still open or not.
